# Generated by Django 3.1.6 on 2021-08-27 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('text', models.TextField()),
                ('technologies', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('url', models.TextField(blank=True, max_length=250)),
                ('uitgelicht', models.BooleanField(default=False)),
            ],
        ),
    ]
