# Generated by Django 3.1.6 on 2021-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210828_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
    ]
