# Generated by Django 3.1.6 on 2021-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210830_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=250)),
                ('image', models.ImageField(default='static/portfolio/assets/images/profile.jpg', upload_to='portfolio/images/')),
            ],
        ),
    ]
