# Generated by Django 3.1.6 on 2021-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_vaardigheid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaardigheid_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaardigheid', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vaardigheid_overig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaardigheid', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vaardigheid_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaardigheid', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Vaardigheid',
        ),
    ]
