# Generated by Django 3.1.6 on 2021-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='image',
            field=models.ImageField(default='static/portfolio/assets/images/profile.jpg', upload_to='portfolio/images/'),
        ),
    ]
