# Generated by Django 3.1.6 on 2021-08-25 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_intro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
