# Generated by Django 3.1.6 on 2021-08-27 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210827_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
