# Generated by Django 3.1.6 on 2021-08-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210827_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
